forge "http://forge.puppetlabs.com"

mod 'debian_base',
    :git => 'https://github.com/synyx/puppet-debian-base.git',
    :ref => 'master'

mod 'mongodb',
    :git => 'https://github.com/synyx/puppet-mongodb.git',
    :ref => 'master'

